CREATE DATABASE IF NOT EXISTS DIUDB;        # CREATE THE DATABASE

USE DIUDB;                                 # USING THE DATABASE        

CREATE TABLE IF NOT EXISTS STUDENT (
      ID INT PRIMARY KEY,
      NAME VARCHAR(50) NOT NULL, 
      SECTION VARCHAR(5) DEFAULT "Z",               # DECLARE THE TABLE STRUCTURE
      AGE INT CHECK (AGE >= 18 ),
      CITY VARCHAR(50) NOT NULL
	);
    
    INSERT INTO STUDENT (ID , NAME , SECTION , AGE , CITY)
    VALUES 
         (1,"TauFique","65_K",22,"COMILLA"),
         (2,"RAFI","65_K",23,"GAZIPUR"),
         (3,"AKASH","65_B",19,"NOAKHALI"),
         (4,"SINTHIA","65_C",21,"TANGAIL"),
         (5,"RAFA","65_T",26,"JOSSOR"),
         (6,"RIPA","65_M",24,"LAKSMIPUR"),                #INSERT VALUE
         (7,"BAYZID","65_W",27,"COMILLA"),
         (8,"OPU","65_P",25,"BRHAMMANBARIA"),
         (9,"SAMI","65_A",22,"SAVAR"),
         (10,"SHAOWN","65_F",26,"GAZIPUR"),
         (11,"ZIAD","65_D",23,"MIRPUR") ;
         
SELECT NAME,ID,SECTION,CITY FROM STUDENT;
SELECT * FROM STUDENT;

INSERT INTO STUDENT (ID , NAME , AGE , CITY)               #TO INSERT VALUE WITHOUT DEFAULT VALUE
VALUES 
      (12,"OMIO",24,"BOGURA");
      
      
UPDATE STUDENT 
SET SECTION = "65_K" WHERE ID = 3;

UPDATE STUDENT                                              #TO UPDATE VALUE RATHER THAN PRIMARY KEY
SET AGE = 20 WHERE SECTION = "65_K";

DELETE FROM STUDENT 
WHERE ID = 3;

UPDATE STUDENT
SET NAME = "CHAPPRI" WHERE ID = 8;                           #TO UPDATE VALUE USING PRIMARY KEY

ALTER TABLE STUDENT
ADD COLUMN GENDER VARCHAR(50) DEFAULT "MALE";                #TO ADD ANOTHER COLUMN

ALTER TABLE STUDENT RENAME COLUMN GENDER TO MARITAL_STATUS;  #TO RENAME THE TABLE HEADING

UPDATE STUDENT SET 
MARITAL_STATUS = "UNMARRIED";                               # SET AN DEFAUT VALUES

SELECT * FROM STUDENT;

SELECT NAME FROM STUDENT WHERE ID = 1;    

SELECT * FROM STUDENT WHERE ID = 1;

SELECT NAME,CITY,AGE FROM STUDENT WHERE SECTION = "65_K";

SELECT DISTINCT CITY,SECTION FROM STUDENT;

SELECT * FROM STUDENT WHERE CITY = "COMILLA" OR CITY = "GAZIPUR";  # LOGICAL OR

SELECT * FROM STUDENT WHERE (CITY = "COMILLA" OR CITY = "GAZIPUR") AND AGE >= 22; # LOGICAL AND

SELECT * FROM STUDENT WHERE NOT AGE = 20;         #LOGICAL NOT

SELECT * FROM STUDENT WHERE CITY IN ("COMILLA","TANGAIL","BRHAMMANBARIA"); # LOGICAL IN

SELECT * FROM STUDENT WHERE AGE  BETWEEN 20 AND 22;      # LOGICAL BETWEEN OPERATOR

SELECT * FROM STUDENT WHERE NAME LIKE  "_A%";

SELECT * FROM STUDENT WHERE NAME LIKE  "B%";             # LOGICAL LIKE OPERATOR

SELECT * FROM STUDENT WHERE NAME LIKE  "%I%";

SELECT MIN(AGE) FROM STUDENT;

SELECT MAX(AGE) FROM STUDENT;

SELECT SUM(AGE) FROM STUDENT;
														# AGGRIGATE FUNCTIONS
SELECT AVG(AGE) FROM STUDENT;

SELECT COUNT(DISTINCT AGE) FROM STUDENT;

SELECT COUNT(DISTINCT CITY) AS NUMBER_OF_CITYS FROM STUDENT;
