CREATE DATABASE IF NOT EXISTS EMPLOYEE;

USE EMPLOYEE;

CREATE TABLE IF NOT EXISTS EMPINFO (
     ID INT PRIMARY KEY,
     FIRST_NAME VARCHAR(50) NOT NULL,
     LAST_NAME VARCHAR(50) NOT NULL,
     DEPERTMENT VARCHAR(50) NOT NULL,
     SALARY INT NOT NULL,
     HIREDATE DATE NOT NULL
);

INSERT INTO EMPINFO (ID,FIRST_NAME,LAST_NAME,DEPERTMENT,SALARY,HIREDATE)
VALUES 
      (1,"JOHN","DEO","HR",50000,'2022-01-10'),
      (2,"JANE","SMITH","IT",60000,'2023-03-12'),
      (3,"ALICE","JOHNSON","HR",35000,'2020-05-03'),
      (4,"BOB","BROWN","FINANCE",62000,'2021-05-15'),
      (5,"CHARLIE","DAVINS","IT",75000,'2017-04-17');
      
SELECT * FROM EMPINFO;

UPDATE EMPINFO 
SET SALARY = 65000 WHERE ID = 5;

ALTER TABLE EMPINFO 
ADD GENDER VARCHAR(50) DEFAULT "MALE";

DELETE FROM EMPINFO
WHERE DEPARTMENT = "FINANCE";

ALTER TABLE EMPINFO RENAME COLUMN HIREDATE TO JOINDATE;

SELECT FIRST_NAME FROM EMPINFO WHERE ID = 3;
SELECT * FROM EMPINFO WHERE ID = 5;

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPINFO WHERE DEPERTMENT = "HR";

SELECT DISTINCT DEPERTMENT FROM EMPINFO;

SELECT * FROM EMPINFO WHERE DEPERTMENT = "IT" OR DEPERTMENT = "HR";


SELECT * FROM EMPINFO WHERE (DEPERTMENT = "IT" OR DEPERTMENT = "HR") AND SALARY >= 50000;

SELECT * FROM EMPINFO WHERE DEPERTMENT IN ("HR","IT","FINANCE");

SELECT * FROM EMPINFO WHERE SALARY BETWEEN 50000 AND 80000;

SELECT * FROM EMPINFO WHERE NOT SALARY = 50000;

SELECT * FROM EMPINFO WHERE FIRST_NAME LIKE "A%";

SELECT * FROM EMPINFO WHERE FIRST_NAME LIKE "%A%";

SELECT * FROM EMPINFO WHERE FIRST_NAME LIKE "%A_";

SELECT MIN(SALARY) FROM EMPINFO ;
SELECT MAX(SALARY) FROM EMPINFO ;
SELECT SUM(SALARY) FROM EMPINFO ;
SELECT AVG(SALARY) FROM EMPINFO ;
SELECT COUNT(DISTINCT DEPERTMENT) FROM EMPINFO ;

SELECT COUNT(DISTINCT DEPERTMENT) AS NO_OF_DEPERTMENT FROM EMPINFO ;







